# Build ancillary library

CFLAGS = -Wall -fPIC -g -O2 -DNDEBUG -DSPARE_SEND_FDS -DSPARE_RECV_FDS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
OBJS = fd_send.o fd_recv.o
TARGET = libancillary.a

all: $(TARGET)

$(TARGET): $(OBJS)
	ar cr $(TARGET) $(OBJS)
	ranlib $(TARGET)

fd_send.o: fd_send.c
	$(CC) $(CFLAGS) -c -o $@ $<

fd_recv.o: fd_recv.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean